"""Dashboard generation and report export, against the real datasets."""

from __future__ import annotations

import io
import json

import pandas as pd
import pytest

from core.charts import build_figure
from core.dashboard import build as build_dashboard
from core.engine import DataSession
from core.models import ChartSpec
from core.reports import to_excel, to_html, to_markdown
from tests.conftest import requires_real_data

RETAIL = "online_retail_ii_international"


# --------------------------------------------------------------------------- #
# Dashboard
# --------------------------------------------------------------------------- #
@requires_real_data
def test_dashboard_uses_the_derived_revenue_metric(real_session: DataSession) -> None:
    """The real retail table has quantity and price but no revenue column.

    A dashboard headlining 'total quantity' would be misleading, so the measure
    expression must be the product and it must be disclosed in the notes.
    """
    dash = build_dashboard(real_session, RETAIL)
    assert dash.measure_expression == "quantity * price"
    assert any("computed as" in n for n in dash.notes)
    labels = [k.label.lower() for k in dash.kpis]
    assert any("revenue" in label for label in labels)


@requires_real_data
def test_dashboard_kpis_are_populated(real_session: DataSession) -> None:
    dash = build_dashboard(real_session, RETAIL)
    assert len(dash.kpis) >= 4
    rows = next(k for k in dash.kpis if k.label == "Rows")
    assert rows.value == "86,041"
    period = next(k for k in dash.kpis if k.label == "Period")
    assert period.value.startswith("2009-12")


@requires_real_data
def test_dashboard_panels_render_and_carry_their_sql(real_session: DataSession) -> None:
    dash = build_dashboard(real_session, RETAIL)
    assert len(dash.panels) >= 3

    kinds = {p.spec.type.value for p in dash.panels}
    assert "line" in kinds, "a dated table should produce a trend panel"
    assert "horizontal_bar" in kinds, "dimensions should produce ranking panels"

    for panel in dash.panels:
        assert panel.sql.lower().startswith("select")
        assert panel.rows, f"panel '{panel.title}' returned no rows"
        frame = pd.DataFrame(panel.rows, columns=panel.columns)
        # Must actually render, not merely hold data.
        assert build_figure(panel.spec, frame).data


@requires_real_data
def test_dashboard_panel_sql_passes_the_guard(real_session: DataSession) -> None:
    """Dashboard SQL is generated by our own code, but it goes through the same
    guard as model-generated SQL — no bypass path exists."""
    dash = build_dashboard(real_session, RETAIL)
    for panel in dash.panels:
        result, guard = real_session.execute_sql(panel.sql)
        assert guard.tables == [RETAIL]
        assert result.row_count >= 0


@requires_real_data
def test_dashboard_trend_matches_the_ground_truth(real_session: DataSession) -> None:
    from evals.ground_truth import monthly_revenue

    truth = monthly_revenue()
    dash = build_dashboard(real_session, RETAIL)
    trend = next(p for p in dash.panels if p.spec.type.value == "line")
    frame = pd.DataFrame(trend.rows, columns=trend.columns)
    assert len(frame) == truth.value["periods"]
    best = frame.loc[frame[trend.spec.y].idxmax()]
    assert best["month"] == truth.value["best_period"]
    assert best[trend.spec.y] == pytest.approx(truth.value["best_value"], rel=1e-6)


@requires_real_data
def test_dashboard_is_json_serialisable(real_session: DataSession) -> None:
    json.dumps(build_dashboard(real_session, RETAIL).to_dict())


@requires_real_data
def test_dashboard_works_on_the_reference_table(real_session: DataSession) -> None:
    """A lookup table with no date column must still produce something sensible."""
    dash = build_dashboard(real_session, "world_bank_country_profile")
    assert dash.kpis
    assert all(p.spec.type.value != "line" for p in dash.panels), "no date column, no trend"


def test_dashboard_on_a_table_with_no_measures() -> None:
    session = DataSession()
    session.add_csv_bytes(
        b"code,label\n" + b"".join(f"c{i},label {i}\n".encode() for i in range(40)), "codes.csv"
    )
    try:
        dash = build_dashboard(session, "codes")
        assert dash.kpis  # row count at minimum
        assert dash.notes or dash.panels
    finally:
        session.close()


# --------------------------------------------------------------------------- #
# Reports
# --------------------------------------------------------------------------- #
@requires_real_data
def test_markdown_report_includes_real_schema_and_provenance(real_session: DataSession) -> None:
    text = to_markdown(real_session)
    assert RETAIL in text
    assert "86,041" in text
    assert "invoicedate" in text
    assert "value overlap" in text, "detected join keys should be documented"
    assert "SQL executed against the uploaded data" in text


@requires_real_data
def test_html_report_is_self_contained_and_escaped(real_session: DataSession) -> None:
    html = to_html(real_session)
    assert html.startswith("<!DOCTYPE html>")
    assert "<style>" in html
    assert "<script" not in html.lower(), "the export must not carry executable script"


@requires_real_data
def test_excel_export_is_a_valid_multi_sheet_workbook(real_session: DataSession) -> None:
    payload = to_excel(real_session)
    assert payload[:2] == b"PK", "xlsx is a zip archive"

    book = pd.ExcelFile(io.BytesIO(payload), engine="openpyxl")
    assert "Overview" in book.sheet_names
    assert any(name.startswith("schema_") for name in book.sheet_names)

    overview = book.parse("Overview")
    assert set(overview["table"]) == set(real_session.table_names)
    assert int(overview.loc[overview["table"] == RETAIL, "rows"].iloc[0]) == 86_041

    schema = book.parse(next(n for n in book.sheet_names if n.startswith("schema_")))
    assert {"column", "type", "role", "null_pct"} <= set(schema.columns)


@requires_real_data
def test_excel_sheet_names_stay_within_excel_limits(real_session: DataSession) -> None:
    book = pd.ExcelFile(io.BytesIO(to_excel(real_session)), engine="openpyxl")
    for name in book.sheet_names:
        assert len(name) <= 31, f"'{name}' exceeds Excel's 31-character sheet-name limit"
        assert not set(name) & set("[]:*?/\\")
    assert len(set(n.lower() for n in book.sheet_names)) == len(book.sheet_names)


@requires_real_data
def test_excel_includes_conversation_artifacts(fake_provider_factory) -> None:
    from core.agent import Agent
    from tests.conftest import ScriptedTurn

    from tests.conftest import RETAIL_CSV

    # A fresh session so the exported conversation contains exactly one turn.
    session = DataSession()
    session.add_csv_path(RETAIL_CSV)
    try:
        provider = fake_provider_factory(
            [
                ScriptedTurn(tool_calls=[("run_sql", {
                    "sql": f"SELECT country, SUM(quantity*price) AS revenue FROM {RETAIL} "
                           f"GROUP BY 1 ORDER BY 2 DESC LIMIT 5",
                    "purpose": "revenue by country",
                })]),
                ScriptedTurn(text="EIRE leads."),
            ]
        )
        Agent(provider).answer(session, "Which country generated the highest revenue?")

        book = pd.ExcelFile(io.BytesIO(to_excel(session)), engine="openpyxl")
        assert "SQL executed" in book.sheet_names
        result_sheets = [n for n in book.sheet_names if n.startswith("Q1_")]
        assert result_sheets, "the query result should be exported as its own sheet"
        frame = book.parse(result_sheets[0])
        assert len(frame) == 5
        assert "revenue" in [c.lower() for c in frame.columns]
    finally:
        session.close()


def test_reports_handle_an_empty_session() -> None:
    session = DataSession()
    try:
        assert "No questions were asked" in to_markdown(session)
        assert to_html(session).startswith("<!DOCTYPE html>")
        assert to_excel(session)[:2] == b"PK"
    finally:
        session.close()
